name: 🚨 Hotfix
description: Correção urgente em produção
title: "HF-2026-[CLIENTE]-001 | Descrição curta do hotfix"
labels: ["hotfix", "priority-high"]

body:
  - type: input
    id: identificador
    attributes:
      label: Identificador da Issue
      description: Siga o padrão HF-ANO-[CLIENTE]-SEQUENCIAL
      placeholder: "Ex: HF-2026-cliente-x-003"
    validations:
      required: true

  - type: input
    id: cliente
    attributes:
      label: Cliente
      placeholder: "Ex: cliente-x"
    validations:
      required: true

  - type: textarea
    id: descricao
    attributes:
      label: Problema em Produção
    validations:
      required: true

  - type: textarea
    id: impacto
    attributes:
      label: Impacto no Negócio
